import './App.css';
import WebWorkerTester from './WebWorkerTester';

function App() {
    return (
        <div className="App">
          <div>Just a web worker test.</div>
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
          <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
            <WebWorkerTester />
        </div>
    );
}

export default App;
